init:
  - git config --global core.autocrlf input
  
image: 
  - Visual Studio 2017

cache:
  - src\packages -> **\packages.config
  - tools -> build.cake

build_script: 
  - ps: .\build.ps1

after_build:
  - ps: $env:IS_PRERELEASE = if($env:APPVEYOR_REPO_TAG_NAME -and $env:APPVEYOR_REPO_TAG_NAME.split('-')[1].length -gt 0){$true}else{$false}

artifacts: 
  - path: artifacts\*
    name: SwashbuckleAspNetVersioningShim

deploy:
  - provider: GitHub
    description: Release of SwashbuckleAspNetVersioningShim
    auth_token:
      secure: 5lhtYmrK8GyagLOZFAIKcCnLrYU62nz3nYYwdb4xWobiTmZ92qfAn3+7g+kmasCf
    artifact: /.*\.nupkg/
    draft: false
    prerelease: $(IS_PRERELEASE)
    on:
      branch: master
      appveyor_repo_tag: true
  - provider: NuGet
    server: https://www.myget.org/F/rh072005/api/v2/package
    api_key:
      secure: xslJdZlEXsrdzucocErMW6yYuLA4rkFLpnrSHGS7AS0rHwvq5ZkxW4l28RVOJiwI
    on:
      branch: master
      appveyor_repo_tag: true
  - provider: NuGet
    api_key:
      secure: 9QA8Ig9g0bNgjwAOv8xRfFsYxvQTuFaL7rR0GKwNEOBFKMdQvXkFwMsotIR9EslX
    on:
      branch: master
      appveyor_repo_tag: true

test: off
